# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import hypergraph_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='features.proto',
  package='',
  serialized_pb='\n\x0e\x66\x65\x61tures.proto\x1a\x10hypergraph.proto:!\n\x07node_fv\x12\x10.Hypergraph.Node\x18\x64 \x01(\t:!\n\x07\x65\x64ge_fv\x12\x10.Hypergraph.Edge\x18\x64 \x01(\tB\x02H\x01')


NODE_FV_FIELD_NUMBER = 100
node_fv = descriptor.FieldDescriptor(
  name='node_fv', full_name='node_fv', index=0,
  number=100, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
EDGE_FV_FIELD_NUMBER = 100
edge_fv = descriptor.FieldDescriptor(
  name='edge_fv', full_name='edge_fv', index=1,
  number=100, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


hypergraph_pb2.Hypergraph.Node.RegisterExtension(node_fv)
hypergraph_pb2.Hypergraph.Edge.RegisterExtension(edge_fv)
# @@protoc_insertion_point(module_scope)
