# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hypergraph.proto',
  package='',
  serialized_pb='\n\x10hypergraph.proto\"\xd2\x01\n\nHypergraph\x12\x0c\n\x04root\x18\x05 \x02(\x05\x12\x1e\n\x04node\x18\x06 \x03(\x0b\x32\x10.Hypergraph.Node\x1aH\n\x04Node\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\x1e\n\x04\x65\x64ge\x18\x03 \x03(\x0b\x32\x10.Hypergraph.Edge*\x05\x08\x64\x10\xc8\x01\x1a?\n\x04\x45\x64ge\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\x15\n\rtail_node_ids\x18\x03 \x03(\x05*\x05\x08\x64\x10\xc8\x01*\x04\x08\x01\x10\x05*\x05\x08\x64\x10\xc8\x01\x42\x02H\x01')




_HYPERGRAPH_NODE = descriptor.Descriptor(
  name='Node',
  full_name='Hypergraph.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Hypergraph.Node.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='Hypergraph.Node.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='edge', full_name='Hypergraph.Node.edge', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 200), ],
  serialized_start=81,
  serialized_end=153,
)

_HYPERGRAPH_EDGE = descriptor.Descriptor(
  name='Edge',
  full_name='Hypergraph.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Hypergraph.Edge.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='Hypergraph.Edge.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tail_node_ids', full_name='Hypergraph.Edge.tail_node_ids', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 200), ],
  serialized_start=155,
  serialized_end=218,
)

_HYPERGRAPH = descriptor.Descriptor(
  name='Hypergraph',
  full_name='Hypergraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='root', full_name='Hypergraph.root', index=0,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='node', full_name='Hypergraph.node', index=1,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HYPERGRAPH_NODE, _HYPERGRAPH_EDGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1, 5), (100, 200), ],
  serialized_start=21,
  serialized_end=231,
)

_HYPERGRAPH_NODE.fields_by_name['edge'].message_type = _HYPERGRAPH_EDGE
_HYPERGRAPH_NODE.containing_type = _HYPERGRAPH;
_HYPERGRAPH_EDGE.containing_type = _HYPERGRAPH;
_HYPERGRAPH.fields_by_name['node'].message_type = _HYPERGRAPH_NODE
DESCRIPTOR.message_types_by_name['Hypergraph'] = _HYPERGRAPH

class Hypergraph(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Node(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _HYPERGRAPH_NODE
    
    # @@protoc_insertion_point(class_scope:Hypergraph.Node)
  
  class Edge(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _HYPERGRAPH_EDGE
    
    # @@protoc_insertion_point(class_scope:Hypergraph.Edge)
  DESCRIPTOR = _HYPERGRAPH
  
  # @@protoc_insertion_point(class_scope:Hypergraph)

# @@protoc_insertion_point(module_scope)
