# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import hypergraph_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='dep.proto',
  package='',
  serialized_pb='\n\tdep.proto\x1a\x10hypergraph.proto\" \n\x03\x44\x65p\x12\x0c\n\x04head\x18\x01 \x02(\x05\x12\x0b\n\x03mod\x18\x02 \x02(\x05:#\n\x03\x64\x65p\x12\x10.Hypergraph.Edge\x18n \x01(\x0b\x32\x04.Dep:!\n\x07has_dep\x12\x10.Hypergraph.Edge\x18o \x01(\x08:\x18\n\x03len\x12\x0b.Hypergraph\x18\x01 \x01(\x05')


DEP_FIELD_NUMBER = 110
dep = descriptor.FieldDescriptor(
  name='dep', full_name='dep', index=0,
  number=110, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
HAS_DEP_FIELD_NUMBER = 111
has_dep = descriptor.FieldDescriptor(
  name='has_dep', full_name='has_dep', index=1,
  number=111, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
LEN_FIELD_NUMBER = 1
len = descriptor.FieldDescriptor(
  name='len', full_name='len', index=2,
  number=1, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_DEP = descriptor.Descriptor(
  name='Dep',
  full_name='Dep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='head', full_name='Dep.head', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mod', full_name='Dep.mod', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['Dep'] = _DEP

class Dep(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEP
  
  # @@protoc_insertion_point(class_scope:Dep)

dep.message_type = _DEP
hypergraph_pb2.Hypergraph.Edge.RegisterExtension(dep)
hypergraph_pb2.Hypergraph.Edge.RegisterExtension(has_dep)
hypergraph_pb2.Hypergraph.RegisterExtension(len)
# @@protoc_insertion_point(module_scope)
