# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import hypergraph_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='lexical.proto',
  package='',
  serialized_pb='\n\rlexical.proto\x1a\x10hypergraph.proto:!\n\x07is_word\x12\x10.Hypergraph.Node\x18n \x01(\x08:\x1e\n\x04word\x12\x10.Hypergraph.Node\x18o \x01(\t')


IS_WORD_FIELD_NUMBER = 110
is_word = descriptor.FieldDescriptor(
  name='is_word', full_name='is_word', index=0,
  number=110, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
WORD_FIELD_NUMBER = 111
word = descriptor.FieldDescriptor(
  name='word', full_name='word', index=1,
  number=111, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


hypergraph_pb2.Hypergraph.Node.RegisterExtension(is_word)
hypergraph_pb2.Hypergraph.Node.RegisterExtension(word)
# @@protoc_insertion_point(module_scope)
