all: hypergraphs.py hypergraphs.rst hmm.py hmm.rst EditDistance.py EditDistance.rst decipher.py decipher.rst parsing.py parsing.rst sequence_crf.py sequence_crf.rst BuildingHypergraph.py BuildingHypergraph.rst Fibonacci.py Fibonacci.rst

hypergraphs.py: hypergraphs.ipynb
	ipython nbconvert --to python hypergraphs.ipynb

hypergraphs.rst: hypergraphs.ipynb
	ipython nbconvert --to rst hypergraphs.ipynb

hmm.py: hmm.ipynb
	ipython nbconvert --to python hmm.ipynb

hmm.rst: hmm.ipynb
	ipython nbconvert --to rst hmm.ipynb

EditDistance.py: EditDistance.ipynb
	ipython nbconvert --to python EditDistance.ipynb

EditDistance.rst: EditDistance.ipynb
	ipython nbconvert --to rst EditDistance.ipynb

decipher.py: decipher.ipynb
	ipython nbconvert --to python decipher.ipynb

decipher.rst: decipher.ipynb
	ipython nbconvert --to rst decipher.ipynb

parsing.py: parsing.ipynb
	ipython nbconvert --to python parsing.ipynb

parsing.rst: parsing.ipynb
	ipython nbconvert --to rst parsing.ipynb

sequence_crf.py: sequence_crf.ipynb
	ipython nbconvert --to python sequence_crf.ipynb

sequence_crf.rst: sequence_crf.ipynb
	ipython nbconvert --to rst sequence_crf.ipynb

BuildingHypergraph.py: BuildingHypergraph.ipynb
	ipython nbconvert --to python BuildingHypergraph.ipynb

BuildingHypergraph.rst: BuildingHypergraph.ipynb
	ipython nbconvert --to rst BuildingHypergraph.ipynb


Fibonacci.py: Fibonacci.ipynb
	ipython nbconvert --to python Fibonacci.ipynb

Fibonacci.rst: Fibonacci.ipynb
	ipython nbconvert --to rst Fibonacci.ipynb
