// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dep.proto

#ifndef PROTOBUF_dep_2eproto__INCLUDED
#define PROTOBUF_dep_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "hypergraph.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dep_2eproto();
void protobuf_AssignDesc_dep_2eproto();
void protobuf_ShutdownFile_dep_2eproto();

class Dep;

// ===================================================================

class Dep : public ::google::protobuf::Message {
 public:
  Dep();
  virtual ~Dep();
  
  Dep(const Dep& from);
  
  inline Dep& operator=(const Dep& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Dep& default_instance();
  
  void Swap(Dep* other);
  
  // implements Message ----------------------------------------------
  
  Dep* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Dep& from);
  void MergeFrom(const Dep& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 head = 1;
  inline bool has_head() const;
  inline void clear_head();
  static const int kHeadFieldNumber = 1;
  inline ::google::protobuf::int32 head() const;
  inline void set_head(::google::protobuf::int32 value);
  
  // required int32 mod = 2;
  inline bool has_mod() const;
  inline void clear_mod();
  static const int kModFieldNumber = 2;
  inline ::google::protobuf::int32 mod() const;
  inline void set_mod(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Dep)
 private:
  inline void set_has_head();
  inline void clear_has_head();
  inline void set_has_mod();
  inline void clear_has_mod();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 head_;
  ::google::protobuf::int32 mod_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_dep_2eproto();
  friend void protobuf_AssignDesc_dep_2eproto();
  friend void protobuf_ShutdownFile_dep_2eproto();
  
  void InitAsDefaultInstance();
  static Dep* default_instance_;
};
// ===================================================================

static const int kDepFieldNumber = 110;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph_Edge,
    ::google::protobuf::internal::MessageTypeTraits< ::Dep >, 11, false >
  dep;
static const int kHasDepFieldNumber = 111;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph_Edge,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  has_dep;
static const int kLenFieldNumber = 1;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  len;

// ===================================================================

// Dep

// required int32 head = 1;
inline bool Dep::has_head() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Dep::set_has_head() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Dep::clear_has_head() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Dep::clear_head() {
  head_ = 0;
  clear_has_head();
}
inline ::google::protobuf::int32 Dep::head() const {
  return head_;
}
inline void Dep::set_head(::google::protobuf::int32 value) {
  set_has_head();
  head_ = value;
}

// required int32 mod = 2;
inline bool Dep::has_mod() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Dep::set_has_mod() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Dep::clear_has_mod() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Dep::clear_mod() {
  mod_ = 0;
  clear_has_mod();
}
inline ::google::protobuf::int32 Dep::mod() const {
  return mod_;
}
inline void Dep::set_mod(::google::protobuf::int32 value) {
  set_has_mod();
  mod_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dep_2eproto__INCLUDED
