// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "features.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {


}  // namespace


void protobuf_AssignDesc_features_2eproto() {
  protobuf_AddDesc_features_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "features.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_features_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_features_2eproto() {
}

void protobuf_AddDesc_features_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_hypergraph_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016features.proto\032\020hypergraph.proto:!\n\007no"
    "de_fv\022\020.Hypergraph.Node\030d \001(\t:!\n\007edge_fv"
    "\022\020.Hypergraph.Edge\030d \001(\tB\002H\001", 108);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "features.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::Hypergraph_Node::default_instance(),
    100, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::Hypergraph_Edge::default_instance(),
    100, 9, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_features_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_features_2eproto {
  StaticDescriptorInitializer_features_2eproto() {
    protobuf_AddDesc_features_2eproto();
  }
} static_descriptor_initializer_features_2eproto_;

const ::std::string node_fv_default("");
::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph_Node,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  node_fv(kNodeFvFieldNumber, node_fv_default);
const ::std::string edge_fv_default("");
::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph_Edge,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  edge_fv(kEdgeFvFieldNumber, edge_fv_default);

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
