// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lexical.proto

#ifndef PROTOBUF_lexical_2eproto__INCLUDED
#define PROTOBUF_lexical_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "hypergraph.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lexical_2eproto();
void protobuf_AssignDesc_lexical_2eproto();
void protobuf_ShutdownFile_lexical_2eproto();


// ===================================================================


// ===================================================================

static const int kIsWordFieldNumber = 110;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph_Node,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  is_word;
static const int kWordFieldNumber = 111;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph_Node,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  word;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lexical_2eproto__INCLUDED
