// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tag.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Tagging_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Tagging_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_tag_2eproto() {
  protobuf_AddDesc_tag_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tag.proto");
  GOOGLE_CHECK(file != NULL);
  Tagging_descriptor_ = file->message_type(0);
  static const int Tagging_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tagging, ind_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tagging, tag_id_),
  };
  Tagging_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Tagging_descriptor_,
      Tagging::default_instance_,
      Tagging_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tagging, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tagging, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Tagging));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tag_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Tagging_descriptor_, &Tagging::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_tag_2eproto() {
  delete Tagging::default_instance_;
  delete Tagging_reflection_;
}

void protobuf_AddDesc_tag_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_hypergraph_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\ttag.proto\032\020hypergraph.proto\"&\n\007Tagging"
    "\022\013\n\003ind\030\001 \002(\005\022\016\n\006tag_id\030\002 \002(\005:+\n\007tagging"
    "\022\020.Hypergraph.Node\030x \001(\0132\010.Tagging:%\n\013ha"
    "s_tagging\022\020.Hypergraph.Node\030y \001(\010", 153);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tag.proto", &protobuf_RegisterTypes);
  Tagging::default_instance_ = new Tagging();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::Hypergraph_Node::default_instance(),
    120, 11, false, false,
    &::Tagging::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::Hypergraph_Node::default_instance(),
    121, 8, false, false);
  Tagging::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tag_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tag_2eproto {
  StaticDescriptorInitializer_tag_2eproto() {
    protobuf_AddDesc_tag_2eproto();
  }
} static_descriptor_initializer_tag_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int Tagging::kIndFieldNumber;
const int Tagging::kTagIdFieldNumber;
#endif  // !_MSC_VER

Tagging::Tagging()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Tagging::InitAsDefaultInstance() {
}

Tagging::Tagging(const Tagging& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Tagging::SharedCtor() {
  _cached_size_ = 0;
  ind_ = 0;
  tag_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Tagging::~Tagging() {
  SharedDtor();
}

void Tagging::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Tagging::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Tagging::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Tagging_descriptor_;
}

const Tagging& Tagging::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tag_2eproto();  return *default_instance_;
}

Tagging* Tagging::default_instance_ = NULL;

Tagging* Tagging::New() const {
  return new Tagging;
}

void Tagging::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    ind_ = 0;
    tag_id_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Tagging::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 ind = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ind_)));
          set_has_ind();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_tag_id;
        break;
      }
      
      // required int32 tag_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_tag_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tag_id_)));
          set_has_tag_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Tagging::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 ind = 1;
  if (has_ind()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ind(), output);
  }
  
  // required int32 tag_id = 2;
  if (has_tag_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->tag_id(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Tagging::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 ind = 1;
  if (has_ind()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->ind(), target);
  }
  
  // required int32 tag_id = 2;
  if (has_tag_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->tag_id(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Tagging::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 ind = 1;
    if (has_ind()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->ind());
    }
    
    // required int32 tag_id = 2;
    if (has_tag_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->tag_id());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Tagging::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Tagging* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Tagging*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Tagging::MergeFrom(const Tagging& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ind()) {
      set_ind(from.ind());
    }
    if (from.has_tag_id()) {
      set_tag_id(from.tag_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Tagging::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Tagging::CopyFrom(const Tagging& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Tagging::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void Tagging::Swap(Tagging* other) {
  if (other != this) {
    std::swap(ind_, other->ind_);
    std::swap(tag_id_, other->tag_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Tagging::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Tagging_descriptor_;
  metadata.reflection = Tagging_reflection_;
  return metadata;
}

::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph_Node,
    ::google::protobuf::internal::MessageTypeTraits< ::Tagging >, 11, false >
  tagging(kTaggingFieldNumber, ::Tagging::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph_Node,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  has_tagging(kHasTaggingFieldNumber, false);

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
