// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: translation.proto

#ifndef PROTOBUF_translation_2eproto__INCLUDED
#define PROTOBUF_translation_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "hypergraph.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_translation_2eproto();
void protobuf_AssignDesc_translation_2eproto();
void protobuf_ShutdownFile_translation_2eproto();


// ===================================================================


// ===================================================================

static const int kForeignSentenceFieldNumber = 1;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  foreign_sentence;
static const int kReferenceSentencesFieldNumber = 2;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Hypergraph,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  reference_sentences;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_translation_2eproto__INCLUDED
