Import('env')

sources = [
    "Hypergraph/Hypergraph.cpp",
    "Hypergraph/Algorithms.cpp",
    "Hypergraph/Semirings.cpp",
    "Hypergraph/Factory.cpp",
    "Hypergraph/BeamSearch.cpp",
    #"Hypergraph/Subgradient.cpp",

    ]

hyp_lib = env.Library('decoding', sources)

Return('hyp_lib')
