Import('env')

sources = [
    "Hypergraph/Hypergraph.cpp",
    "Hypergraph/SemiringAlgorithms.cpp",
    "Hypergraph/Algorithms.cpp",
    "Hypergraph/Semirings.cpp",
    "Hypergraph/BeamSearch.cpp",
    ]

hyp_lib = env.Library('decoding', sources)

Return('hyp_lib')
