Import('env')

sources = [
    "Hypergraph/Hypergraph.cpp",
    "Hypergraph/Algorithms.cpp",
    "Hypergraph/Constraints.cpp",
    "Hypergraph/Subgradient.cpp",

    ]

hyp_lib = env.Library('decoding', sources)

Return('hyp_lib')
